/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exosupermarcher;

import classMetier.Employe;
import classMetier.Rayon;
import classMetier.Secteur;
import classMetier.Travailler;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noasillam
 */
public class frmSupermarche extends javax.swing.JFrame {

    /**
     * Creates new form frmSupermarche
     */
    
    
     ArrayList<Secteur> mesSecteurs;
             
             
             
    public frmSupermarche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblSupermarché = new javax.swing.JScrollPane();
        tblInfos = new javax.swing.JTable();
        lblInfGeneral = new javax.swing.JLabel();
        lblSupermarche = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        txtNomEmploye = new javax.swing.JTextField();
        txtMoyen = new javax.swing.JTextField();
        lblTempMoyen = new javax.swing.JLabel();
        btnRecherche = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalEmploye = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblInfos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tblInfos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numéro secteur", "nom secteur", "numero du rayon", "nom du rayon", "numéro employé", "nom employé"
            }
        ));
        tblSupermarché.setViewportView(tblInfos);

        lblInfGeneral.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblInfGeneral.setText("Informations générales");

        lblSupermarche.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSupermarche.setText("Projet supermarché");
        lblSupermarche.setSize(new java.awt.Dimension(45, 20));

        lblInfo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblInfo.setText("Temps de travail d'un employé");

        lblTempMoyen.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTempMoyen.setText("Temps moyen");

        btnRecherche.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRecherche.setText("Rechercher");
        btnRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechercheMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("temps total employé ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(lblSupermarche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tblSupermarché, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTempMoyen)
                        .addGap(18, 18, 18)
                        .addComponent(txtMoyen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecherche))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(txtTotalEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSupermarche)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo)
                    .addComponent(lblInfGeneral))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecherche)
                            .addComponent(txtNomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTempMoyen)
                            .addComponent(txtMoyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tblSupermarché, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        DefaultTableModel dtmInfos = new DefaultTableModel();
        dtmInfos = (DefaultTableModel) tblInfos.getModel();
        Vector v;
        
        Secteur sec1 = new Secteur(1, "Multimédia");
        Secteur sec2 = new Secteur(2, "Electromenager");
        
        Rayon ray1 = new Rayon(1, "Television");
        Rayon ray2 = new Rayon(2, "Informatique");
        Rayon ray3 = new Rayon(3, "Lave vaisselle");
        
        Employe emp1 = new Employe(1, "Marie");
        Employe emp2 = new Employe(2, "Stephanie");
        Employe emp3 = new Employe(3, "Karim");
        Employe emp4 = new Employe(4, "Pierre");
        Employe emp5 = new Employe(5, "Lucille");
        
        
        Travailler trav1 = new Travailler(emp1, 4);
        Travailler trav2 = new Travailler(emp2, 8);
        Travailler trav3 = new Travailler(emp3, 1);        
        Travailler trav4 = new Travailler(emp4, 5);        
        Travailler trav5 = new Travailler(emp5, 6);
        Travailler trav6 = new Travailler(emp1, 8);
        Travailler trav7 = new Travailler(emp2, 3);
        
        ray1.getLesTravailler().add(trav1);
        ray1.getLesTravailler().add(trav2);
        ray2.getLesTravailler().add(trav3);
        ray2.getLesTravailler().add(trav4);
        ray3.getLesTravailler().add(trav5);
        ray3.getLesTravailler().add(trav6);
        ray3.getLesTravailler().add(trav7);
        
        sec1.getLesRayons().add(ray1);
        sec1.getLesRayons().add(ray2);
        sec2.getLesRayons().add(ray3);
        
        mesSecteurs = new ArrayList();
        
        mesSecteurs.add(sec1);
        mesSecteurs.add(sec2);
                        
        int tempsTotal = 0;
        int nbEmployes = 0;
        
        for (Secteur sec : mesSecteurs)
        {
            for(Rayon ray : sec.getLesRayons())
            {
                for(Travailler trav : ray.getLesTravailler()){
                    nbEmployes++;
                    tempsTotal = tempsTotal + trav.getTempsPasse();
                    
                    v = new Vector ();
                    v.add(sec.getIdSecteur());
                    v.add(sec.getNomSecteur());
                    v.add(ray.getIdRayon());
                    v.add(ray.getNomRayon());
                    v.add(trav.getUnEmploye().getIdEmploye());
                    v.add(trav.getUnEmploye().getNomEmploye());
                    dtmInfos.addRow(v);
                }
            }
        }
        
       txtMoyen.setText( String.valueOf(tempsTotal / nbEmployes)); 
    }//GEN-LAST:event_formWindowOpened

    private void btnRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechercheMouseClicked
        // TODO add your handling code here:
        if(txtNomEmploye.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this,"Veuillez saisir le nom de l'employé");
        }
        else{
           String nomMin = txtNomEmploye.getText().toLowerCase();
          String nomOk = nomMin.substring(0, 1).toUpperCase() + nomMin.substring(1);
          
          int tempsTotal = 0;
          int nbFois = 0;
           for (Secteur sec : mesSecteurs)
        {
            for(Rayon ray : sec.getLesRayons())
            {
                for(Travailler trav : ray.getLesTravailler()){
                    if(trav.getUnEmploye().getNomEmploye().compareTo(nomOk) == 0)
                    {
                       tempsTotal = tempsTotal + trav.getTempsPasse();
                       nbFois++;
                    }
                }
            }
        }
         if(tempsTotal == 0)
         {
             txtTotalEmploye.setText("Employe inconnu");
         }
         else{
              txtTotalEmploye.setText(String.valueOf((double)tempsTotal / nbFois));
         }
        }
    }//GEN-LAST:event_btnRechercheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSupermarche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSupermarche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSupermarche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSupermarche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSupermarche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfGeneral;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSupermarche;
    private javax.swing.JLabel lblTempMoyen;
    private javax.swing.JTable tblInfos;
    private javax.swing.JScrollPane tblSupermarché;
    private javax.swing.JTextField txtMoyen;
    private javax.swing.JTextField txtNomEmploye;
    private javax.swing.JTextField txtTotalEmploye;
    // End of variables declaration//GEN-END:variables
}
